# Generated by Django 2.2.6 on 2020-01-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_auto_20200112_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
